# Generated by Django 5.1.3 on 2024-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
